# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: TEST

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    services: 
      database: 
        image: couchbase
        ports: 
          - 8091-8097:8091-8097
          - 9123:9123
          - 9140:9140
          - 11210:11210
          - 11280:11280
          - 11207:11207
          - 18091-18097:18091-18097
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    
    - run: yarn load:scripts
    - run: yarn load:proto
    - run: yarn install
    - run: yarn run:test
    - run: yarn run:test:e2e  
