# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  create-db:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      couchbase:
        # Docker Hub image
        image: couchbase
        run: couchbase-cli cluster-init -c 0.0.0.0 \
          --cluster-username administrator \
          --cluster-password administrator \
          --services data,index,query \
          --cluster-ramsize 512 \
          --cluster-index-ramsize 256
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install
    - run: yarn test
    - run: yarn test:e2e
